export const PATHS = {
  root: '/',
  dev: '/dev',
  profile: '/profile',
  dashboard: '/dashboard',
  product: '/product',
  category: '/category',
  importOrder: '/import-order',
  order: '/order',
  store: '/store',
  customer: '/customer',
  staff: '/staff',
  signIn: '/login',
  logout: '/logout',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
};
